language: node_js
node_js:
  - "6"

services:
  - mongodb

cache:
  directories:
    - "node_modules"
    - "bower_components"

script:
  - npm run lint
  - npm run babel
  - npm run webpack
  - npm run test
  - npm run esdoc

after_success:
  - if [ $TRAVIS_BRANCH = 'master' ]; then ./.travis/build_docs.sh; fi
