language: node_js
node_js:
  - "6"

services:
  - mongodb

cache:
  directories:
    - "node_modules"
    - "bower_components"

script:
  - npm run lint
  - npm run babel
  - npm run webpack
  - npm run test
  - npm run esdoc

deploy:
  provider: pages
  skip-cleanup: true
  github-token: ${GH_TOKEN}
  keep-history: true
  on:
    branch: master
  local-dir: docs
  target-branch: gh-pages
