version: 0.0

os: linux

files:
  - source: ./
    destination: /home/ec2-user/gcc_website
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/deploy/npm-install.sh
      runas: ec2-user
      timeout: 300
  ApplicationStart:
    - location: scripts/deploy/npm-start.sh
      runas: ec2-user
      timeout: 60
  ValidateService:
    - location: scripts/deploy/validate-service.sh
      runas: root
      timeout: 180
