window.esdocSearchIndex = [
  [
    "gcc_website/src/client/components/aspectratio.jsx~aspectratio",
    "function/index.html#static-function-AspectRatio",
    "<span>AspectRatio</span> <span class=\"search-result-import-path\">gcc_website/src/client/components/AspectRatio.jsx</span>",
    "function"
  ],
  [
    "gcc_website/src/client/pages/asyncpage.jsx~asyncpage",
    "variable/index.html#static-variable-AsyncPage",
    "<span>AsyncPage</span> <span class=\"search-result-import-path\">gcc_website/src/client/pages/AsyncPage.jsx</span>",
    "variable"
  ],
  [
    "gcc_website/src/client/components/backgroundimage.jsx~backgroundimage",
    "function/index.html#static-function-BackgroundImage",
    "<span>BackgroundImage</span> <span class=\"search-result-import-path\">gcc_website/src/client/components/BackgroundImage.jsx</span>",
    "function"
  ],
  [
    "gcc_website/src/client/components/banner.jsx~banner",
    "function/index.html#static-function-Banner",
    "<span>Banner</span> <span class=\"search-result-import-path\">gcc_website/src/client/components/Banner.jsx</span>",
    "function"
  ],
  [
    "gcc_website/src/client/pages/beliefs.jsx~beliefspage",
    "variable/index.html#static-variable-BeliefsPage",
    "<span>BeliefsPage</span> <span class=\"search-result-import-path\">gcc_website/src/client/pages/Beliefs.jsx</span>",
    "variable"
  ],
  [
    "gcc_website/src/client/components/center.jsx~center",
    "function/index.html#static-function-Center",
    "<span>Center</span> <span class=\"search-result-import-path\">gcc_website/src/client/components/Center.jsx</span>",
    "function"
  ],
  [
    "gcc_website/src/client/components/eventbox.jsx~eventbox",
    "function/index.html#static-function-EventBox",
    "<span>EventBox</span> <span class=\"search-result-import-path\">gcc_website/src/client/components/EventBox.jsx</span>",
    "function"
  ],
  [
    "gcc_website/src/client/components/event.jsx~eventcomponent",
    "function/index.html#static-function-EventComponent",
    "<span>EventComponent</span> <span class=\"search-result-import-path\">gcc_website/src/client/components/Event.jsx</span>",
    "function"
  ],
  [
    "gcc_website/src/client/pages/events.jsx~eventspage",
    "variable/index.html#static-variable-EventsPage",
    "<span>EventsPage</span> <span class=\"search-result-import-path\">gcc_website/src/client/pages/Events.jsx</span>",
    "variable"
  ],
  [
    "gcc_website/src/client/pages/familygroup.jsx~familygrouppage",
    "variable/index.html#static-variable-FamilyGroupPage",
    "<span>FamilyGroupPage</span> <span class=\"search-result-import-path\">gcc_website/src/client/pages/FamilyGroup.jsx</span>",
    "variable"
  ],
  [
    "gcc_website/src/client/components/footer.jsx~footer",
    "function/index.html#static-function-Footer",
    "<span>Footer</span> <span class=\"search-result-import-path\">gcc_website/src/client/components/Footer.jsx</span>",
    "function"
  ],
  [
    "gcc_website/src/client/pages/home.jsx~homepage",
    "variable/index.html#static-variable-HomePage",
    "<span>HomePage</span> <span class=\"search-result-import-path\">gcc_website/src/client/pages/Home.jsx</span>",
    "variable"
  ],
  [
    "gcc_website/src/client/components/jumbotron.jsx~jumbotron",
    "function/index.html#static-function-Jumbotron",
    "<span>Jumbotron</span> <span class=\"search-result-import-path\">gcc_website/src/client/components/Jumbotron.jsx</span>",
    "function"
  ],
  [
    "gcc_website/src/client/components/lora.jsx~lora",
    "function/index.html#static-function-Lora",
    "<span>Lora</span> <span class=\"search-result-import-path\">gcc_website/src/client/components/Lora.jsx</span>",
    "function"
  ],
  [
    "gcc_website/src/client/modules/modeldata.js~model_data_loaded",
    "variable/index.html#static-variable-MODEL_DATA_LOADED",
    "<span>MODEL_DATA_LOADED</span> <span class=\"search-result-import-path\">gcc_website/src/client/modules/modelData.js</span>",
    "variable"
  ],
  [
    "gcc_website/src/client/templates/maintemplate.jsx~maintemplate",
    "function/index.html#static-function-MainTemplate",
    "<span>MainTemplate</span> <span class=\"search-result-import-path\">gcc_website/src/client/templates/MainTemplate.jsx</span>",
    "function"
  ],
  [
    "gcc_website/src/client/pages/ministries.jsx~ministriespage",
    "variable/index.html#static-variable-MinistriesPage",
    "<span>MinistriesPage</span> <span class=\"search-result-import-path\">gcc_website/src/client/pages/Ministries.jsx</span>",
    "variable"
  ],
  [
    "gcc_website/src/client/pages/multimedia.jsx~multimediapage",
    "variable/index.html#static-variable-MultimediaPage",
    "<span>MultimediaPage</span> <span class=\"search-result-import-path\">gcc_website/src/client/pages/Multimedia.jsx</span>",
    "variable"
  ],
  [
    "gcc_website/src/client/components/navbar.jsx~navbar",
    "class/src/client/components/Navbar.jsx~Navbar.html",
    "<span>Navbar</span> <span class=\"search-result-import-path\">gcc_website/src/client/components/Navbar.jsx</span>",
    "class"
  ],
  [
    "gcc_website/src/client/components/navbardropdown.jsx~navbardropdown",
    "function/index.html#static-function-NavbarDropdown",
    "<span>NavbarDropdown</span> <span class=\"search-result-import-path\">gcc_website/src/client/components/NavbarDropdown.jsx</span>",
    "function"
  ],
  [
    "gcc_website/src/client/pages/notfound.jsx~notfoundpage",
    "variable/index.html#static-variable-NotFoundPage",
    "<span>NotFoundPage</span> <span class=\"search-result-import-path\">gcc_website/src/client/pages/NotFound.jsx</span>",
    "variable"
  ],
  [
    "gcc_website/src/client/components/optional.jsx~optional",
    "function/index.html#static-function-Optional",
    "<span>Optional</span> <span class=\"search-result-import-path\">gcc_website/src/client/components/Optional.jsx</span>",
    "function"
  ],
  [
    "gcc_website/src/client/modules/page.js~page_loaded",
    "variable/index.html#static-variable-PAGE_LOADED",
    "<span>PAGE_LOADED</span> <span class=\"search-result-import-path\">gcc_website/src/client/modules/page.js</span>",
    "variable"
  ],
  [
    "gcc_website/src/server/pagerouter.jsx~pagerouter",
    "function/index.html#static-function-PageRouter",
    "<span>PageRouter</span> <span class=\"search-result-import-path\">gcc_website/src/server/pageRouter.jsx</span>",
    "function"
  ],
  [
    "gcc_website/src/models/s3resource.js~s3resource",
    "variable/index.html#static-variable-S3Resource",
    "<span>S3Resource</span> <span class=\"search-result-import-path\">gcc_website/src/models/s3resource.js</span>",
    "variable"
  ],
  [
    "gcc_website/src/models/s3resource.js~s3resourceschema",
    "variable/index.html#static-variable-S3ResourceSchema",
    "<span>S3ResourceSchema</span> <span class=\"search-result-import-path\">gcc_website/src/models/s3resource.js</span>",
    "variable"
  ],
  [
    "gcc_website/src/client/modules/metadata.js~set_title",
    "variable/index.html#static-variable-SET_TITLE",
    "<span>SET_TITLE</span> <span class=\"search-result-import-path\">gcc_website/src/client/modules/metadata.js</span>",
    "variable"
  ],
  [
    "gcc_website/src/client/pages/staff.jsx~staffpage",
    "variable/index.html#static-variable-StaffPage",
    "<span>StaffPage</span> <span class=\"search-result-import-path\">gcc_website/src/client/pages/Staff.jsx</span>",
    "variable"
  ],
  [
    "gcc_website/src/client/components/tile.jsx~tile",
    "function/index.html#static-function-Tile",
    "<span>Tile</span> <span class=\"search-result-import-path\">gcc_website/src/client/components/Tile.jsx</span>",
    "function"
  ],
  [
    "gcc_website/src/client/components/tiledeck.jsx~tiledeck",
    "function/index.html#static-function-TileDeck",
    "<span>TileDeck</span> <span class=\"search-result-import-path\">gcc_website/src/client/components/TileDeck.jsx</span>",
    "function"
  ],
  [
    "gcc_website/src/client/components/titlebanner.jsx~titlebanner",
    "function/index.html#static-function-TitleBanner",
    "<span>TitleBanner</span> <span class=\"search-result-import-path\">gcc_website/src/client/components/TitleBanner.jsx</span>",
    "function"
  ],
  [
    "gcc_website/src/client/pages/welcome.jsx~welcomepage",
    "variable/index.html#static-variable-WelcomePage",
    "<span>WelcomePage</span> <span class=\"search-result-import-path\">gcc_website/src/client/pages/Welcome.jsx</span>",
    "variable"
  ],
  [
    "gcc_website/src/client/hoc/asynccomponent.jsx~asynccomponent",
    "function/index.html#static-function-asyncComponent",
    "<span>asyncComponent</span> <span class=\"search-result-import-path\">gcc_website/src/client/hoc/asyncComponent.jsx</span>",
    "function"
  ],
  [
    "gcc_website/src/client/modules/contentful.js~client",
    "variable/index.html#static-variable-client",
    "<span>client</span> <span class=\"search-result-import-path\">gcc_website/src/client/modules/contentful.js</span>",
    "variable"
  ],
  [
    "gcc_website/src/client/modules/modeldata.js~fetchmodeldata",
    "function/index.html#static-function-fetchModelData",
    "<span>fetchModelData</span> <span class=\"search-result-import-path\">gcc_website/src/client/modules/modelData.js</span>",
    "function"
  ],
  [
    "gcc_website/src/client/modules/page.js~fetchpage",
    "function/index.html#static-function-fetchPage",
    "<span>fetchPage</span> <span class=\"search-result-import-path\">gcc_website/src/client/modules/page.js</span>",
    "function"
  ],
  [
    "gcc_website/src/client/modules/metadata.js~metadata",
    "function/index.html#static-function-metadata",
    "<span>metadata</span> <span class=\"search-result-import-path\">gcc_website/src/client/modules/metadata.js</span>",
    "function"
  ],
  [
    "gcc_website/src/client/modules/modeldata.js~page",
    "function/index.html#static-function-page",
    "<span>page</span> <span class=\"search-result-import-path\">gcc_website/src/client/modules/modelData.js</span>",
    "function"
  ],
  [
    "gcc_website/src/client/modules/page.js~page",
    "function/index.html#static-function-page",
    "<span>page</span> <span class=\"search-result-import-path\">gcc_website/src/client/modules/page.js</span>",
    "function"
  ],
  [
    "gcc_website/src/client/modules/index.js~rootreducer",
    "variable/index.html#static-variable-rootReducer",
    "<span>rootReducer</span> <span class=\"search-result-import-path\">gcc_website/src/client/modules/index.js</span>",
    "variable"
  ],
  [
    "gcc_website/src/server/api/index.js~router",
    "variable/index.html#static-variable-router",
    "<span>router</span> <span class=\"search-result-import-path\">gcc_website/src/server/api/index.js</span>",
    "variable"
  ],
  [
    "gcc_website/src/client/routes.js~routes",
    "variable/index.html#static-variable-routes",
    "<span>routes</span> <span class=\"search-result-import-path\">gcc_website/src/client/routes.js</span>",
    "variable"
  ],
  [
    "gcc_website/src/models/helpers/aws.js~s3bucket",
    "function/index.html#static-function-s3Bucket",
    "<span>s3Bucket</span> <span class=\"search-result-import-path\">gcc_website/src/models/helpers/aws.js</span>",
    "function"
  ],
  [
    "gcc_website/src/client/modules/metadata.js~settitle",
    "function/index.html#static-function-setTitle",
    "<span>setTitle</span> <span class=\"search-result-import-path\">gcc_website/src/client/modules/metadata.js</span>",
    "function"
  ],
  [
    "gcc_website/src/client/hoc/withtitle.jsx~withtitle",
    "function/index.html#static-function-withTitle",
    "<span>withTitle</span> <span class=\"search-result-import-path\">gcc_website/src/client/hoc/withTitle.jsx</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/client/app.jsx",
    "file/src/client/app.jsx.html",
    "src/client/app.jsx",
    "file"
  ],
  [
    "src/client/components/aspectratio.jsx",
    "file/src/client/components/AspectRatio.jsx.html",
    "src/client/components/AspectRatio.jsx",
    "file"
  ],
  [
    "src/client/components/backgroundimage.jsx",
    "file/src/client/components/BackgroundImage.jsx.html",
    "src/client/components/BackgroundImage.jsx",
    "file"
  ],
  [
    "src/client/components/banner.jsx",
    "file/src/client/components/Banner.jsx.html",
    "src/client/components/Banner.jsx",
    "file"
  ],
  [
    "src/client/components/bannerbibleverse.jsx",
    "file/src/client/components/BannerBibleVerse.jsx.html",
    "src/client/components/BannerBibleVerse.jsx",
    "file"
  ],
  [
    "src/client/components/center.jsx",
    "file/src/client/components/Center.jsx.html",
    "src/client/components/Center.jsx",
    "file"
  ],
  [
    "src/client/components/event.jsx",
    "file/src/client/components/Event.jsx.html",
    "src/client/components/Event.jsx",
    "file"
  ],
  [
    "src/client/components/eventbox.jsx",
    "file/src/client/components/EventBox.jsx.html",
    "src/client/components/EventBox.jsx",
    "file"
  ],
  [
    "src/client/components/footer.jsx",
    "file/src/client/components/Footer.jsx.html",
    "src/client/components/Footer.jsx",
    "file"
  ],
  [
    "src/client/components/head.jsx",
    "file/src/client/components/Head.jsx.html",
    "src/client/components/Head.jsx",
    "file"
  ],
  [
    "src/client/components/jumbotron.jsx",
    "file/src/client/components/Jumbotron.jsx.html",
    "src/client/components/Jumbotron.jsx",
    "file"
  ],
  [
    "src/client/components/lora.jsx",
    "file/src/client/components/Lora.jsx.html",
    "src/client/components/Lora.jsx",
    "file"
  ],
  [
    "src/client/components/navbar.jsx",
    "file/src/client/components/Navbar.jsx.html",
    "src/client/components/Navbar.jsx",
    "file"
  ],
  [
    "src/client/components/navbar.jsx~navbar#close",
    "class/src/client/components/Navbar.jsx~Navbar.html#instance-method-close",
    "src/client/components/Navbar.jsx~Navbar#close",
    "method"
  ],
  [
    "src/client/components/navbar.jsx~navbar#constructor",
    "class/src/client/components/Navbar.jsx~Navbar.html#instance-constructor-constructor",
    "src/client/components/Navbar.jsx~Navbar#constructor",
    "method"
  ],
  [
    "src/client/components/navbar.jsx~navbar#navlinklist",
    "class/src/client/components/Navbar.jsx~Navbar.html#instance-member-navLinkList",
    "src/client/components/Navbar.jsx~Navbar#navLinkList",
    "member"
  ],
  [
    "src/client/components/navbar.jsx~navbar#open",
    "class/src/client/components/Navbar.jsx~Navbar.html#instance-method-open",
    "src/client/components/Navbar.jsx~Navbar#open",
    "method"
  ],
  [
    "src/client/components/navbar.jsx~navbar#render",
    "class/src/client/components/Navbar.jsx~Navbar.html#instance-method-render",
    "src/client/components/Navbar.jsx~Navbar#render",
    "method"
  ],
  [
    "src/client/components/navbar.jsx~navbar#state",
    "class/src/client/components/Navbar.jsx~Navbar.html#instance-member-state",
    "src/client/components/Navbar.jsx~Navbar#state",
    "member"
  ],
  [
    "src/client/components/navbar.jsx~navbar#toggle",
    "class/src/client/components/Navbar.jsx~Navbar.html#instance-method-toggle",
    "src/client/components/Navbar.jsx~Navbar#toggle",
    "method"
  ],
  [
    "src/client/components/navbar.jsx~navbar.defaultprops",
    "class/src/client/components/Navbar.jsx~Navbar.html#static-get-defaultProps",
    "src/client/components/Navbar.jsx~Navbar.defaultProps",
    "member"
  ],
  [
    "src/client/components/navbar.jsx~navbar.proptypes",
    "class/src/client/components/Navbar.jsx~Navbar.html#static-get-propTypes",
    "src/client/components/Navbar.jsx~Navbar.propTypes",
    "member"
  ],
  [
    "src/client/components/navbar.test.jsx",
    "file/src/client/components/Navbar.test.jsx.html",
    "src/client/components/Navbar.test.jsx",
    "file"
  ],
  [
    "src/client/components/navbardropdown.jsx",
    "file/src/client/components/NavbarDropdown.jsx.html",
    "src/client/components/NavbarDropdown.jsx",
    "file"
  ],
  [
    "src/client/components/optional.jsx",
    "file/src/client/components/Optional.jsx.html",
    "src/client/components/Optional.jsx",
    "file"
  ],
  [
    "src/client/components/tile.jsx",
    "file/src/client/components/Tile.jsx.html",
    "src/client/components/Tile.jsx",
    "file"
  ],
  [
    "src/client/components/tiledeck.jsx",
    "file/src/client/components/TileDeck.jsx.html",
    "src/client/components/TileDeck.jsx",
    "file"
  ],
  [
    "src/client/components/titlebanner.jsx",
    "file/src/client/components/TitleBanner.jsx.html",
    "src/client/components/TitleBanner.jsx",
    "file"
  ],
  [
    "src/client/hoc/asynccomponent.jsx",
    "file/src/client/hoc/asyncComponent.jsx.html",
    "src/client/hoc/asyncComponent.jsx",
    "file"
  ],
  [
    "src/client/hoc/withtitle.jsx",
    "file/src/client/hoc/withTitle.jsx.html",
    "src/client/hoc/withTitle.jsx",
    "file"
  ],
  [
    "src/client/modules/contentful.js",
    "file/src/client/modules/contentful.js.html",
    "src/client/modules/contentful.js",
    "file"
  ],
  [
    "src/client/modules/index.js",
    "file/src/client/modules/index.js.html",
    "src/client/modules/index.js",
    "file"
  ],
  [
    "src/client/modules/metadata.js",
    "file/src/client/modules/metadata.js.html",
    "src/client/modules/metadata.js",
    "file"
  ],
  [
    "src/client/modules/modeldata.js",
    "file/src/client/modules/modelData.js.html",
    "src/client/modules/modelData.js",
    "file"
  ],
  [
    "src/client/modules/page.js",
    "file/src/client/modules/page.js.html",
    "src/client/modules/page.js",
    "file"
  ],
  [
    "src/client/pages/asyncpage.jsx",
    "file/src/client/pages/AsyncPage.jsx.html",
    "src/client/pages/AsyncPage.jsx",
    "file"
  ],
  [
    "src/client/pages/beliefs.jsx",
    "file/src/client/pages/Beliefs.jsx.html",
    "src/client/pages/Beliefs.jsx",
    "file"
  ],
  [
    "src/client/pages/events.jsx",
    "file/src/client/pages/Events.jsx.html",
    "src/client/pages/Events.jsx",
    "file"
  ],
  [
    "src/client/pages/familygroup.jsx",
    "file/src/client/pages/FamilyGroup.jsx.html",
    "src/client/pages/FamilyGroup.jsx",
    "file"
  ],
  [
    "src/client/pages/home.jsx",
    "file/src/client/pages/Home.jsx.html",
    "src/client/pages/Home.jsx",
    "file"
  ],
  [
    "src/client/pages/ministries.jsx",
    "file/src/client/pages/Ministries.jsx.html",
    "src/client/pages/Ministries.jsx",
    "file"
  ],
  [
    "src/client/pages/multimedia.jsx",
    "file/src/client/pages/Multimedia.jsx.html",
    "src/client/pages/Multimedia.jsx",
    "file"
  ],
  [
    "src/client/pages/notfound.jsx",
    "file/src/client/pages/NotFound.jsx.html",
    "src/client/pages/NotFound.jsx",
    "file"
  ],
  [
    "src/client/pages/page.jsx",
    "file/src/client/pages/Page.jsx.html",
    "src/client/pages/Page.jsx",
    "file"
  ],
  [
    "src/client/pages/staff.jsx",
    "file/src/client/pages/Staff.jsx.html",
    "src/client/pages/Staff.jsx",
    "file"
  ],
  [
    "src/client/pages/welcome.jsx",
    "file/src/client/pages/Welcome.jsx.html",
    "src/client/pages/Welcome.jsx",
    "file"
  ],
  [
    "src/client/routes.js",
    "file/src/client/routes.js.html",
    "src/client/routes.js",
    "file"
  ],
  [
    "src/client/templates/maintemplate.jsx",
    "file/src/client/templates/MainTemplate.jsx.html",
    "src/client/templates/MainTemplate.jsx",
    "file"
  ],
  [
    "src/config.js",
    "file/src/config.js.html",
    "src/config.js",
    "file"
  ],
  [
    "src/main.js",
    "file/src/main.js.html",
    "src/main.js",
    "file"
  ],
  [
    "src/models/helpers/aws.js",
    "file/src/models/helpers/aws.js.html",
    "src/models/helpers/aws.js",
    "file"
  ],
  [
    "src/models/s3resource.js",
    "file/src/models/s3resource.js.html",
    "src/models/s3resource.js",
    "file"
  ],
  [
    "src/nconf-browser.js",
    "file/src/nconf-browser.js.html",
    "src/nconf-browser.js",
    "file"
  ],
  [
    "src/server/api/index.js",
    "file/src/server/api/index.js.html",
    "src/server/api/index.js",
    "file"
  ],
  [
    "src/server/app.js",
    "file/src/server/app.js.html",
    "src/server/app.js",
    "file"
  ],
  [
    "src/server/pagerouter.jsx",
    "file/src/server/pageRouter.jsx.html",
    "src/server/pageRouter.jsx",
    "file"
  ]
]